### ISSUE TITLE
Verification Email Goes To Promotions

### ISSUE THREAD

**Issue by noahboila** [thelecter/Baithub-Issues#1]
Verification Email Goes To Promotions
Steps To Fix
Avoid email blast (use email campaigns) ...
Avoid too many links. ...
Improve your sender reputation. ...
Keep the HTML to text ratio. ...
Personalize your email. ...
Avoid spam trigger words. ...
Use correct formatting. ...
Declutter the footer.

**Comment by thelecter** [comment]
Changed text formatting. Emails no longer going to promotions or spam.
